### PR TITLE
Create sk.json

### PR DESCRIPTION
**Pull request by misa1515**
Created new translation in slovak language

### CODE REVIEW

**Comment by mauro-midolo** [comment]
Hello @misa1515,
Could you please change text from english to Slovak?

Thanks
Mauro

**Review by mauro-midolo — CHANGES_REQUESTED** [review]
Could you please change text from english to Slovak?

**Comment by misa1515** [comment]
Hello @mauro-midolo,
done.
Thank you for your work.

**Review by mauro-midolo — APPROVED** [review]

**Comment by mauro-midolo** [comment]
Thank you @misa1515 foto your contribution!

**Pull request merged**
